FROM mvm-jetty-v03

# The below line is only needed if you want to run on your local computer
# ENV GOOGLE_APPLICATION_CREDENTIALS=/app/WEB-INF/YOUR_KEY_FILE.json

ADD target/bigtable-hello-SNAPSHOT/ /app

